### PR TITLE
[R] Ensure our instructions to install vimure v0.1 (latest) in R works

### PR DESCRIPTION
**Pull request by jonjoncardoso**
I need help testing that you can install R on your computers and that it works. 

_Full disclaimer_: personally, I'm finding the R setup a bit cumbersome. I'm [considering refactoring the entire R codebase](https://github.com/latentnetworks/vimure/discussions/66) shortly, so it doesn't depend on python at all.

### Elly
- [ ] Follow the instructions in the [VIMuRe 📦 Installation page](https://latentnetworks.github.io/vimure/latest/install.html). No need to use the package; I want to test the installation at this stage.
- [ ] Let me know if everything worked by replying to this PR. If you encounter an error or anything, please share a screenshot!

### Dan
- [ ] Follow the instructions in the [VIMuRe 📦 Installation page](https://latentnetworks.github.io/vimure/latest/install.html). No need to use the package; I want to test the installation at this stage.
- [ ] Let me know if everything worked by replying to this PR. If you encounter an error or anything, please share a screenshot!

## Text edits?

If you want to amend the text, tell me your suggested changes here or commit directly to this branch `jonjoncardoso/63-update-dev-setup`. You will need to install Quarto and then run: `quarto preview ./docs --render all --no-browser` but [that's about it](https://github.com/latentnetworks/vimure/blob/develop/CONTRIBUTING.md#-building-the-documentation-locally).

### CODE REVIEW

**Comment by eapower** [comment]
Ran into issues. Do we need to require() reticulate after installing? Bigger issue is something to do with CXXFLAGS. Details below:

session info: 
 version  R version 4.2.0 (2022-04-22)
 os       macOS Big Sur 11.6.7
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_GB.UTF-8
 ctype    en_GB.UTF-8
 tz       Europe/London
 date     2023-02-28
 rstudio  2022.07.2+576 Spotted Wakerobin (desktop)
 pandoc   NA

> install.packages("reticulate")
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.2/reticulate_1.28.tgz'
Content type 'application/x-gzip' length 2570415 bytes (2.5 MB)
==================================================
downloaded 2.5 MB


The downloaded binary packages are in
	/var/folders/r_/35wgfv6s4rnd2tt62r7mbd1c0000gn/T//Rtmps13VET/downloaded_packages
> require(devtools)
Loading required package: devtools
Loading required package: usethis
> devtools::install_github("latentnetworks/vimure", subdir="src/R", ref="develop")
Downloading GitHub repo latentnetworks/vimure@develop
Error: Failed to install 'vimure' from GitHub:
  Multiple results for CXXFLAGS found, something is wrong.FALSE

**Comment by jonjoncardoso** [comment]
Thanks @eapower, in theory, we shouldn't `require(reticulate)`, no. 

I will try to find a Mac Virtual Machine to see how to debug the error you reported, as I can't replicate it

> Multiple results for CXXFLAGS found, something is wrong.FALSE

**Comment by gabiborges1** [comment]
I can test on MAC but the multiple CXXFLAGS seems to be a problem with the installation of R.

@eapower Can you try [this](https://github.com/stan-dev/rstan/issues/866#issuecomment-716678581) solution?

Check your Makevars.win file using:
```file.edit(file.path(Sys.getenv("HOME"), ".R", "Makevars.win"))```
And remove duplicated entries

**Comment by eapower** [comment]
the Makevars.win file appears to be empty when I open it. Certainly no duplicates there...

**Comment by eapower** [comment]
Sorry if I scroll down further on the page with the solution, I see a version for mac which is to try 
`file.edit("~/.R/Makevars")`
This locates the right file, but it doesn't show any duplicates. The file contains:
```
CXXFLAGS=-O3 -mtune=native -march=native
CXXFLAGS= -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined
```

**Comment by jonjoncardoso** [comment]
I doubt this is a problem with the R installation itself. It looks like some underlying dependency of vimure relies on running some Rcpp or C/C++ code and for some reason — lack of a C library? — this throws an error. I’ll keep digging how we can debug this…

**Comment by gabiborges1** [comment]
@eapower I'm sorry that the solution didnt work. 

I managed a way of replicating this error on my computer and looks like that we shouldn't have the file "~/.R/Makevars". 
So try to remove it by running on cmd the following command:
```
rm ~/.R/Makevars
```

Then, you would be able to install the package normally (hopefully). 

The package was installed successfully folowing the instructions on MacOs Montrey 12.4

**Comment by eapower** [comment]
FYI, I tried this on another Mac and it worked without issue. The output at the end is:

```
Vimure v ()
Python v3.8 (~/Library/r-miniconda-arm64/envs/r-reticulate/bin/python)
```
So my only question was why it wasn't showing anything with Vimure.

**Comment by eapower** [comment]
And now on a third Mac, a different issue. Output below:



```
> install.packages("reticulate")
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.2/reticulate_1.28.tgz'
Content type 'application/x-gzip' length 2570415 bytes (2.5 MB)
==================================================
downloaded 2.5 MB


The downloaded binary packages are in
	/var/folders/v3/61hlhwwn037fknn2s4m6t5lw0000gn/T//RtmpWRuor9/downloaded_packages
> require(devtools)
Loading required package: devtools
Loading required package: usethis
> devtools::install_github("latentnetworks/vimure", subdir="src/R", ref="develop")
Downloading GitHub repo latentnetworks/vimure@develop
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                              
2: CRAN packages only               
3: None                             
4: Rcpp     (1.0.9 -> 1.0.10) [CRAN]
5: RcppTOML (0.1.7 -> 0.2.2 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
Rcpp     (1.0.9 -> 1.0.10) [CRAN]
RcppTOML (0.1.7 -> 0.2.2 ) [CRAN]
Installing 2 packages: Rcpp, RcppTOML
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.2/Rcpp_1.0.10.tgz'
Content type 'application/x-gzip' length 3240791 bytes (3.1 MB)
==================================================
downloaded 3.1 MB

trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.2/RcppTOML_0.2.2.tgz'
Content type 'application/x-gzip' length 763422 bytes (745 KB)
==================================================
downloaded 745 KB


The downloaded binary packages are in
	/var/folders/v3/61hlhwwn037fknn2s4m6t5lw0000gn/T//RtmpWRuor9/downloaded_packages
✔  checking for file ‘/private/var/folders/v3/61hlhwwn037fknn2s4m6t5lw0000gn/T/RtmpWRuor9/remotesee73882df57/latentnetworks-vimure-f454f88/src/R/DESCRIPTION’ (414ms)
─  preparing ‘vimure’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘vimure_0.1.tar.gz’
   
* installing *source* package ‘vimure’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (vimure)
> require(vimure)
Loading required package: vimure
> vimure::install_vimure()
+ . /Users/ellypower/Library/r-miniconda/bin/activate
+ conda activate '/Users/ellypower/Library/r-miniconda/envs/r-reticulate'
+ '/Users/ellypower/Library/r-miniconda/envs/r-reticulate/bin/python' -m pip install --upgrade --no-user --ignore-installed 'git+https://github.com/latentnetworks/vimure.git@develop#egg=vimure&subdirectory=src/python/'
Collecting vimure
  Cloning https://github.com/latentnetworks/vimure.git (to revision develop) to /private/var/folders/v3/61hlhwwn037fknn2s4m6t5lw0000gn/T/pip-install-d33dsigi/vimure_aa1b7e3f141e4328bce0fefd41352c09
  Running command git clone --filter=blob:none --quiet https://github.com/latentnetworks/vimure.git /private/var/folders/v3/61hlhwwn037fknn2s4m6t5lw0000gn/T/pip-install-d33dsigi/vimure_aa1b7e3f141e4328bce0fefd41352c09
  Running command git checkout -b develop --track origin/develop
  Switched to a new branch 'develop'
  branch 'develop' set up to track 'origin/develop'.
  Resolved https://github.com/latentnetworks/vimure.git to commit f454f88573efcde8f753c9217871972a3eb424b3
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting scikit-tensor-py3@ https://github.com/jonjoncardoso/scikit-tensor-py3/archive/master.zip
  Downloading https://github.com/jonjoncardoso/scikit-tensor-py3/archive/master.zip
     \ 56.8 kB 668.8 kB/s 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting numpy<=1.24.2
  Downloading numpy-1.24.2-cp38-cp38-macosx_10_9_x86_64.whl (19.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 3.5 MB/s eta 0:00:00
Collecting scipy<=1.10.1
  Downloading scipy-1.10.1-cp38-cp38-macosx_10_9_x86_64.whl (35.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.0/35.0 MB 3.7 MB/s eta 0:00:00
Collecting pandas<2.0.0
  Downloading pandas-1.5.3-cp38-cp38-macosx_10_9_x86_64.whl (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 3.8 MB/s eta 0:00:00
Collecting scikit-learn<=1.2.1
  Downloading scikit_learn-1.2.1-cp38-cp38-macosx_10_9_x86_64.whl (9.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━                   5.0/9.0 MB 3.9 MB/s eta 0:00:02
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 435, in _error_catcher
    yield
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 341, in run
    requirement_set = resolver.resolve(
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 291, in __init__
    super().__init__(
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 161, in __init__
    self.dist = self._prepare()
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 230, in _prepare
    dist = self._prepare_distribution()
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 302, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 428, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 473, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 155, in unpack_url
    file = get_http_url(
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 96, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/network/download.py", line 146, in __call__
    for chunk in chunks:
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 538, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ellypower/Library/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
WARNING: There was an error checking the latest version of pip.
Error: Error installing package(s): "'git+https://github.com/latentnetworks/vimure.git@develop#egg=vimure&subdirectory=src/python/'"
```

```
sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6.3

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] vimure_0.1     devtools_2.4.5 usethis_2.1.6 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10       compiler_4.2.2    later_1.3.0       urlchecker_1.0.1  prettyunits_1.1.1
 [6] profvis_0.3.7     remotes_2.4.2     tools_4.2.2       digest_0.6.29     pkgbuild_1.3.1   
[11] pkgload_1.3.2     jsonlite_1.8.4    lattice_0.20-45   memoise_2.0.1     lifecycle_1.0.1  
[16] png_0.1-8         rlang_1.0.6       Matrix_1.5-1      shiny_1.7.1       cli_3.4.1        
[21] rstudioapi_0.13   curl_4.3.2        fastmap_1.1.0     withr_2.5.0       stringr_1.4.0    
[26] fs_1.5.2          htmlwidgets_1.5.4 grid_4.2.2        rprojroot_2.0.3   here_1.0.1       
[31] reticulate_1.28   glue_1.6.2        R6_2.5.1          processx_3.6.1    sessioninfo_1.2.2
[36] callr_3.7.0       purrr_0.3.4       magrittr_2.0.3    ps_1.7.1          promises_1.2.0.1 
[41] ellipsis_0.3.2    htmltools_0.5.2   mime_0.12         xtable_1.8-4      httpuv_1.6.5     
[46] stringi_1.7.6     miniUI_0.1.1.1    cachem_1.0.6      crayon_1.5.1     
```

**Comment by eapower** [comment]
running `reticulate::miniconda_update()` resolved the issue. 

I get as output at the end:
```
Vimure v ()
Python v3.8 (~/Library/r-miniconda/envs/r-reticulate/bin/python)
```

**Comment by jonjoncardoso** [comment]
One of the errors you reported is probably just a temporary internet connection issue:

```
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): 
Read timed out.
```

**Comment by eapower** [comment]
FYI, `rm ~/.R/Makevars` in the Terminal did indeed fix the issue, and have now installed vimure on that Mac, too!

**Pull request merged**
